### ISSUE TITLE
CIF Symettry issues

### ISSUE THREAD

**Issue by kharem21** [SimonEnsemble/PorousMaterials.jl#133]
The second and forth CIF are throwing errors when put into Porous Materials. It has to do with reading symmetry operations. 
https://pubs.acs.org/doi/10.1021/jacs.9b05872
@ahyork

**Comment by ahyork** [comment]
I believe this has to do with whitespace on lines after the symmetry operations, [this PR](https://github.com/SimonEnsemble/PorousMaterials.jl/pull/132) should fix it.
