### ISSUE TITLE
error during importing crystal structure

### ISSUE THREAD

**Issue by gregchung** [SimonEnsemble/PorousMaterials.jl#49]
I am getting the following error while importing a CIF file.

> julia> framework = Framework("FIQCEN_clean_min_charges.cif")
> ERROR: MethodError: Cannot `convert` an object of type String to an object of type PorousMaterials.Framework
> This may have arisen from a call to the constructor PorousMaterials.Framework(...),
> since type constructors fall back to convert methods.
> Stacktrace:
>  [1] PorousMaterials.Framework(::String) at ./sysimg.jl:77

**Comment by SimonEnsemble** [comment]
@gregchung are you on the master branch? `read_crystal_structure_file` is not available right? `read_` then hit tab for tab completion to see if it is there.

**Comment by gregchung** [comment]
@SimonEnsemble I was using Julia-0.6.3 and after upgrading to 0.6.4 and installing dependencies, I am able to import the structures!
