### ISSUE TITLE
Paths and Windows-compatibility

### ISSUE THREAD

**Issue by arosen93** [SimonEnsemble/PorousMaterials.jl#72]
Hi SimonEnsemble! 

It seems that all the paths in `PorousMaterials.jl` are constructed via string concatenation. For greater inter-platform compatibility (notably, to enable compatibility with Windows machines), it's probably better to be constructing paths via `joinpath`, or a similar command. In my fork, I've searched through the code for all instances of path construction and have modified them with `joinpath` statements, so now it runs on my Windows machine (with all tests passing). If this of interest, I'll open a PR once I double-check I got them all. If not, feel free to close the issue.

**Comment by SimonEnsemble** [comment]
hi @arosen93, please do submit a pull request!
I was not aware of this issue since I use Linux. I will start using `joinpath` for now on.
`joinpath("csimon" , "data", "crystals")` gives the same result as string concatenation on my Linux machine.

**Comment by arosen93** [comment]
Great! Will submit the PR tomorrow.
